package dev.otherlode.instrumentation

import dev.otherlode.config.AgentConfig
import dev.otherlode.export.ResourceAttributes
import dev.otherlode.registry.ProbeRegistry
import net.bytebuddy.agent.ByteBuddyAgent
import net.bytebuddy.agent.builder.ResettableClassFileTransformer
import net.bytebuddy.jar.asm.ClassWriter
import net.bytebuddy.jar.asm.Opcodes
import java.io.InputStream
import java.lang.instrument.Instrumentation
import java.lang.ref.Reference
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue
import java.util.logging.Handler as JulHandler
import java.util.logging.Level as JulLevel
import java.util.logging.LogRecord as JulLogRecord
import java.util.logging.Logger as JulLogger

/**
 * Drives probe withholding end to end: ByteBuddy matches and transforms a class whose supertype cannot be
 * defined, [ProbeRegistry.register] commits its probes from `onTransformation` before that failure
 * happens, `defineClass` then raises `NoClassDefFoundError`, and two [LoadedClassSweep] passes
 * withhold the class for good rather than publishing it at zero forever.
 *
 * [DeflectedClassLoadTest] is the closest precedent: both drive the real [OtherlodeInstrumentation]
 * pipeline over a purpose-built classloader to pin one JVM behaviour the design depends on.
 *
 * The fixture classes are generated bytecode, not files under `src/test/java` or
 * `src/test/kotlin`, the shape [TypeMatchPolicyTest] already uses for a synthetic class that must
 * never touch the real classpath. That is not a style choice here: Gradle's JUnit Platform
 * discovery loads every compiled test-source class by name, through the real application
 * classloader, before any `@Test` method runs, to check it for test annotations. A `.class` file
 * on disk under either of those names would already be sitting in
 * [Instrumentation.getAllLoadedClasses] by the time this test's own sweep looks, which
 * [ProbeRegistry.confirmFrom] would read as "defined", regardless of what this test's own loader
 * does. Confirmed directly: with these fixtures as ordinary compiled `.java` files, the withheld
 * test passed alone but failed under `./gradlew build`, and only there.
 */
class ProbesWithheldForUndefinedClassTest {
    private val instrumentation: Instrumentation = ByteBuddyAgent.install()
    private var installedTransformer: ResettableClassFileTransformer? = null
    private var installedOtherlode: OtherlodeInstrumentation? = null

    private companion object {
        const val VANISHING_BASE = "com.example.target.VanishingBase"
        const val VANISHING_SUB = "com.example.target.VanishingSub"
        const val STEADY_BASE = "com.example.target.SteadyBase"
        const val STEADY_SUB = "com.example.target.SteadySub"
        const val SLOW_BASE = "com.example.target.SlowBase"
        const val SLOW_SUB = "com.example.target.SlowSub"

        private fun internalName(dotted: String) = dotted.replace('.', '/')

        /** A public class naming [superName] as its supertype, with no other content. */
        private fun classWithSupertypeOnly(
            name: String,
            superName: String,
        ): ByteArray {
            val writer = ClassWriter(0)
            writer.visit(Opcodes.V17, Opcodes.ACC_PUBLIC or Opcodes.ACC_SUPER, internalName(name), null, internalName(superName), null)
            writer.visitEnd()
            return writer.toByteArray()
        }

        /** Like [classWithSupertypeOnly], plus one public, no-op instance method, for a class the method tier can probe. */
        private fun classWithProbeableMethod(
            name: String,
            superName: String,
            methodName: String,
        ): ByteArray {
            val writer = ClassWriter(0)
            writer.visit(Opcodes.V17, Opcodes.ACC_PUBLIC or Opcodes.ACC_SUPER, internalName(name), null, internalName(superName), null)
            val method = writer.visitMethod(Opcodes.ACC_PUBLIC, methodName, "()V", null, null)
            method.visitCode()
            method.visitInsn(Opcodes.RETURN)
            method.visitMaxs(0, 1)
            method.visitEnd()
            writer.visitEnd()
            return writer.toByteArray()
        }

        private val CLASS_BYTES: Map<String, ByteArray> =
            mapOf(
                VANISHING_BASE to classWithSupertypeOnly(VANISHING_BASE, "java.lang.Object"),
                VANISHING_SUB to classWithProbeableMethod(VANISHING_SUB, VANISHING_BASE, "ping"),
                STEADY_BASE to classWithSupertypeOnly(STEADY_BASE, "java.lang.Object"),
                STEADY_SUB to classWithProbeableMethod(STEADY_SUB, STEADY_BASE, "ping"),
                SLOW_BASE to classWithSupertypeOnly(SLOW_BASE, "java.lang.Object"),
                SLOW_SUB to classWithProbeableMethod(SLOW_SUB, SLOW_BASE, "ping"),
            )
    }

    /**
     * Defines [CLASS_BYTES]'s classes from the bytes generated above, denying [deniedNames]
     * outright in [loadClass] before [findClass] is ever reached, the same shape
     * [FixtureClassLoader] uses for a file on disk.
     *
     * [getResourceAsStream] still serves a denied name's bytes: that is the path ByteBuddy's
     * `net.bytebuddy.dynamic.ClassFileLocator` reads through when it resolves a type description,
     * never [loadClass]. Denying only [loadClass] is what makes `defineClass` fail on the
     * supertype while leaving ByteBuddy able to describe and transform the subclass.
     */
    private class InMemoryDeniedSuperclassLoader(
        parent: ClassLoader,
        private val deniedNames: Set<String>,
    ) : ClassLoader(parent) {
        override fun loadClass(
            name: String,
            resolve: Boolean,
        ): Class<*> {
            if (name in deniedNames) throw ClassNotFoundException(name)
            val bytes = CLASS_BYTES[name] ?: return super.loadClass(name, resolve)
            synchronized(getClassLoadingLock(name)) {
                val existing = findLoadedClass(name)
                val loaded = existing ?: defineClass(name, bytes, 0, bytes.size)
                if (resolve) resolveClass(loaded)
                return loaded
            }
        }

        override fun getResourceAsStream(name: String): InputStream? {
            val dotted = name.removeSuffix(".class").replace('/', '.')
            return CLASS_BYTES[dotted]?.inputStream() ?: super.getResourceAsStream(name)
        }
    }

    /**
     * Like [InMemoryDeniedSuperclassLoader], except [SLOW_BASE] is supplied only after [release]
     * opens. [stalled] opens when the JVM first asks for it, which happens while the JVM defines
     * [SLOW_SUB], after the transformer has run.
     */
    private class StallingSuperclassLoader(
        parent: ClassLoader,
        private val stalled: CountDownLatch,
        private val release: CountDownLatch,
    ) : ClassLoader(parent) {
        override fun loadClass(
            name: String,
            resolve: Boolean,
        ): Class<*> {
            if (name == SLOW_BASE) {
                stalled.countDown()
                release.await()
            }
            val bytes = CLASS_BYTES[name] ?: return super.loadClass(name, resolve)
            synchronized(getClassLoadingLock(name)) {
                val loaded = findLoadedClass(name) ?: defineClass(name, bytes, 0, bytes.size)
                if (resolve) resolveClass(loaded)
                return loaded
            }
        }

        override fun getResourceAsStream(name: String): InputStream? {
            val dotted = name.removeSuffix(".class").replace('/', '.')
            return CLASS_BYTES[dotted]?.inputStream() ?: super.getResourceAsStream(name)
        }
    }

    private fun freshLoader() = InMemoryDeniedSuperclassLoader(javaClass.classLoader, setOf(VANISHING_BASE))

    private fun install(
        registry: ProbeRegistry,
        config: AgentConfig,
    ) {
        val otherlode = OtherlodeInstrumentation(config, registry)
        installedOtherlode = otherlode
        installedTransformer = otherlode.install(instrumentation)
    }

    @AfterTest
    fun tearDown() {
        installedTransformer?.let { installedOtherlode?.uninstall(instrumentation, it) }
        installedTransformer = null
        installedOtherlode = null
    }

    /**
     * Captures the records a [java.lang.System.Logger] obtained for [loggerName] emits, through
     * its default `java.util.logging` backend, mirroring `LoadedClassSweepTest`'s own helper.
     */
    private fun captureLogRecords(
        loggerName: String,
        block: () -> Unit,
    ): List<JulLogRecord> {
        val records = mutableListOf<JulLogRecord>()
        val handler =
            object : JulHandler() {
                override fun publish(record: JulLogRecord) {
                    records += record
                }

                override fun flush() {}

                override fun close() {}
            }
        val julLogger = JulLogger.getLogger(loggerName)
        val originalLevel = julLogger.level
        julLogger.addHandler(handler)
        julLogger.level = JulLevel.ALL
        try {
            block()
        } finally {
            julLogger.removeHandler(handler)
            julLogger.level = originalLevel
        }
        return records
    }

    @Test
    fun `ByteBuddy transforms and registers the subclass before defineClass fails on its unloadable supertype`() {
        val registry = ProbeRegistry()
        install(registry, AgentConfig.parse("includePackages=com.example.target"))

        assertFailsWith<NoClassDefFoundError> { Class.forName(VANISHING_SUB, true, freshLoader()) }

        assertTrue(
            VANISHING_SUB in registry.registeredClassNames(),
            "the transform must have committed this class's probes before the definition failed",
        )
        assertTrue(
            registry
                .manifest(ResourceAttributes("test", null, "instance-1", null, "run-1"))
                .skippedClasses
                .none { it.className == VANISHING_SUB },
            "a class ByteBuddy actually transformed is not a class it skipped",
        )
    }

    @Test
    fun `a class woven and registered but never defined is withheld for good, named once, and absent from the manifest`() {
        val registry = ProbeRegistry(confirmsDefinitions = true)
        val config = AgentConfig.parse("includePackages=com.example.target")
        install(registry, config)
        val sweep = LoadedClassSweep(instrumentation, registry, config)

        val loader = freshLoader()
        assertFailsWith<NoClassDefFoundError> { Class.forName(VANISHING_SUB, true, loader) }

        // Step 2 of the sequence under test: the transform already committed this class's probes,
        // ahead of the two sweeps that follow. A test that skipped this check could pass for the
        // wrong reason, with the class absent from the manifest because it was never registered at
        // all rather than because it was withheld.
        assertTrue(VANISHING_SUB in registry.registeredClassNames())

        val records =
            captureLogRecords(LoadedClassSweep::class.java.name) {
                sweep.run(runForwardPass = false) // first miss
                sweep.run(runForwardPass = false) // second miss, withheld for good
                sweep.run(runForwardPass = false) // already withheld, must not warn again
            }
        // The registry keeps only a WeakReference to loader, and a collected loader is confirmed
        // rather than withheld. loader has no other referent once Class.forName returns, so
        // without this fence the JIT is free to treat it as unreachable before the sweeps above
        // run, which turns this test flaky rather than wrong: the class would be confirmed by the
        // loader-collected path instead of withheld.
        Reference.reachabilityFence(loader)

        val warnings = records.filter { it.level == JulLevel.WARNING && it.message.contains(VANISHING_SUB) }
        assertEquals(1, warnings.size, "a class withheld for good is named once and never again")
        assertEquals(1, registry.withheldForGoodClassCount())
        assertEquals(0, registry.unconfirmedClassCount(), "withheld for good is a terminal state, not an open one")

        val manifest = registry.manifest(ResourceAttributes("test", null, "instance-1", null, "run-1"))
        assertTrue(manifest.probes.none { it.className == VANISHING_SUB }, "withheld for good means never published")
        assertTrue(manifest.skippedClasses.none { it.className == VANISHING_SUB }, "it was registered, not skipped")
        assertTrue(manifest.unreportedClasses.none { it.className == VANISHING_SUB }, "it was registered, not unreported")
        assertEquals(
            listOf(VANISHING_SUB),
            manifest.failedClasses.map { it.className },
            "a class withheld for good is named as failed to load, with none of its probes",
        )
    }

    @Test
    fun `a sibling whose supertype resolves is confirmed by the first sweep and is published`() {
        val registry = ProbeRegistry(confirmsDefinitions = true)
        val config = AgentConfig.parse("includePackages=com.example.target")
        install(registry, config)
        val sweep = LoadedClassSweep(instrumentation, registry, config)

        // SteadyBase is not in the loader's denied set, so this class defines normally. Its probe
        // counts stay at zero: no method on it is ever called, so confirmation can only come from
        // the sweep matching its name in the JVM's loaded set, not from a non-zero count.
        val loader = freshLoader()
        Class.forName(STEADY_SUB, true, loader)

        assertTrue(STEADY_SUB in registry.registeredClassNames())
        sweep.run(runForwardPass = false)
        // Holds loader reachable across the sweep so confirmation is pinned to the loaded-set match
        // this test names, not to the registry's separate "collected loader publishes" fallback,
        // which would also confirm the class and mask what this test is actually proving.
        Reference.reachabilityFence(loader)

        assertEquals(0, registry.unconfirmedClassCount(), "one sweep is enough once the JVM has actually defined the class")
        assertEquals(0, registry.withheldForGoodClassCount())

        val manifest = registry.manifest(ResourceAttributes("test", null, "instance-1", null, "run-1"))
        assertTrue(
            manifest.probes.any { it.className == STEADY_SUB },
            "without this control, withholding the other class would prove nothing: this harness must publish something",
        )
    }

    @Test
    fun `a class whose loader stalls on its supertype is never named failed and is confirmed once it defines`() {
        val registry = ProbeRegistry(confirmsDefinitions = true)
        val config = AgentConfig.parse("includePackages=com.example.target")
        install(registry, config)
        val sweep = LoadedClassSweep(instrumentation, registry, config)
        val stalled = CountDownLatch(1)
        val release = CountDownLatch(1)
        val loader = StallingSuperclassLoader(javaClass.classLoader, stalled, release)
        val defining = Thread({ Class.forName(SLOW_SUB, true, loader) }, "slow-definer")
        defining.start()
        try {
            assertTrue(stalled.await(30, TimeUnit.SECONDS), "the JVM must reach the supertype lookup")
            assertTrue(SLOW_SUB in registry.registeredClassNames(), "the transform runs before the supertype lookup")

            val records =
                captureLogRecords(LoadedClassSweep::class.java.name) {
                    repeat(6) { sweep.run(runForwardPass = false) }
                }

            assertTrue(records.none { it.message.contains(SLOW_SUB) }, "a class still being defined is never named")
            assertEquals(0, registry.withheldForGoodClassCount())
            assertEquals(1, registry.unconfirmedClassCount(), "it stays pending while its definition runs")
            assertTrue(
                registry
                    .manifest(ResourceAttributes("test", null, "instance-1", null, "run-1"))
                    .failedClasses
                    .isEmpty(),
            )
        } finally {
            release.countDown()
            defining.join(30_000)
        }

        sweep.run(runForwardPass = false)
        Reference.reachabilityFence(loader)

        assertEquals(0, registry.unconfirmedClassCount(), "the sweep confirms the class once the JVM has defined it")
        assertEquals(0, registry.withheldForGoodClassCount())
        val manifest = registry.manifest(ResourceAttributes("test", null, "instance-1", null, "run-1"))
        assertTrue(manifest.probes.any { it.className == SLOW_SUB })
        assertTrue(manifest.failedClasses.isEmpty())
    }
}
